[workspace]

members = [
    "gpu_wavefront_pt",
    "wavefront_common",
]

resolver = "2"

[workspace.package]
name = "wave_front_path_tracer"
version = "0.1.0"
authors = ["rchiaramo <rchiaramo@gmail.com>"]
edition = "2021"

[workspace.dependencies]
winit = "0.30.11"
env_logger = "0.11.8"
log = "0.4.27"
wgpu = "25.0.2"
pollster = "0.4.0"
bytemuck = { version = "1.23.0", features = ["derive"] }
glam = "0.30.3"
rand = "0.9.1"
imgui = "0.12.0"
imgui-winit-support = "0.13.0"
imgui-wgpu = "0.25.0"
